DROP TABLE IF EXISTS lobbys, lobby_slots, lobby_members, lobby_requests, lobby_invitations, lobby_bans CASCADE;
DROP TYPE IF EXISTS lobby_privacy, lobby_request_status CASCADE;
/*
code_auth: can_invite
*/
CREATE TYPE lobby_privacy AS ENUM('PRIVATE','DEFAULT');
CREATE TABLE lobbys(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  check_join boolean NOT NULL DEFAULT FALSE,
  privacy lobby_privacy NOT NULL DEFAULT 'DEFAULT'::lobby_privacy,

  id_owner integer REFERENCES users NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE lobby_slots(
  id_lobby integer REFERENCES lobbys ON DELETE CASCADE DEFERRABLE PRIMARY KEY,
  free_slots integer NOT NULL DEFAULT 1,
  max_slots integer NOT NULL DEFAULT 2,
  CHECK(0 <= free_slots  AND 1 < max_slots AND free_slots < max_slots)
);
ALTER TABLE lobbys ADD CONSTRAINT fk_lobby_slots FOREIGN KEY(id) REFERENCES lobby_slots(id_lobby) DEFERRABLE;

CREATE TABLE lobby_members(
  id_lobby integer REFERENCES lobbys,
  id_user integer REFERENCES users UNIQUE,
  PRIMARY KEY(id_lobby, id_user),

	is_owner boolean NOT NULL DEFAULT FALSE,
  joined_at timestamptz NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX idx_unique_lobby_owner ON lobby_members(id_lobby) WHERE is_owner IS TRUE;
ALTER TABLE lobbys ADD CONSTRAINT fk_lobby_owner
  FOREIGN KEY(id, id_owner) REFERENCES lobby_members(id_lobby, id_user) DEFERRABLE;

CREATE TABLE lobby_requests(
  id_lobby integer REFERENCES lobbys ON DELETE CASCADE,
  id_user integer REFERENCES users,
  PRIMARY KEY(id_lobby, id_user),

  need_validation boolean NOT NULL DEFAULT FALSE,
  created_at timestamptz NOT NULL DEFAULT NOW(),

  id_creator integer REFERENCES users DEFAULT NULL, --IS NULL ? is_request : is_invitation
  -- fk_lobby_request_creator (id_lobby, id_user, id_creator) REFERENCES lobby_invitations
  CHECK(id_user IS DISTINCT FROM id_creator)
);
CREATE UNIQUE INDEX idx_unique_user_request ON lobby_requests(id_user) WHERE id_creator IS NOT NULL;

CREATE TABLE lobby_invitations(
  id_lobby integer REFERENCES lobbys ON DELETE CASCADE,
  id_target integer REFERENCES users,
  id_creator integer REFERENCES users,
  PRIMARY KEY(id_lobby, id_target, id_creator),
  --UNIQUE(id_creator, id_target) --useless / lobby_members is unique per user
  CHECK(id_creator<>id_target),

	--FOREIGN KEY(id_creator, id_target) REFERENCES friends?
  FOREIGN KEY(id_lobby, id_creator) REFERENCES lobby_members(id_lobby, id_user) DEFERRABLE,
  FOREIGN KEY(id_lobby, id_target) REFERENCES lobby_requests(id_lobby, id_user) ON DELETE CASCADE
);
ALTER TABLE lobby_requests
  ADD CONSTRAINT fk_lobby_request_creator
    FOREIGN KEY(id_lobby, id_user, id_creator) REFERENCES lobby_invitations(id_lobby, id_target, id_creator) DEFERRABLE;

CREATE TABLE lobby_bans(
  id_lobby integer REFERENCES users,
  id_user integer REFERENCES users,
  PRIMARY KEY(id_lobby, id_user),

  created_at timestamptz NOT NULL DEFAULT NOW(),
  ban_resolved_at timestamptz NOT NULL
);