DROP TABLE IF EXISTS squads, squad_users, squad_invitations CASCADE;

CREATE TABLE squads(
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  private boolean NOT NULL DEFAULT false,
  id_owner integer REFERENCES users NOT NULL UNIQUE,

  free_slots integer NOT NULL DEFAULT 1,
  max_slots integer NOT NULL DEFAULT 2,
  CHECK(0 <= free_slots AND 1 < max_slots AND free_slots < max_slots),
  CHECK(max_slots-free_slots > 1),

  id_lobby integer REFERENCES lobbys,
  waiting_approval boolean, CHECK(waiting_approval OR waiting_approval IS NULL),
  CHECK((id_lobby IS NULL AND waiting_approval IS NULL) OR id_lobby IS NOT NULL)
);

CREATE TABLE squad_users(
  id_squad integer REFERENCES squads,
  id_user integer REFERENCES users,
  PRIMARY KEY(id_squad, id_user),

  --member
  fk_member integer REFERENCES users UNIQUE,
  CHECK(fk_member IS NULL OR fk_member=id_user),
  UNIQUE(id_squad, fk_member),
	--invitation
  fk_invitation integer REFERENCES users,
	pending boolean,
	id_creator integer REFERENCES users,
  CHECK((fk_invitation IS NULL AND pending IS NULL AND id_creator IS NULL) OR (fk_invitation=id_user AND pending IS NOT NULL AND id_creator IS NOT NULL)),
	UNIQUE(id_squad, fk_invitation),
	--ban
  is_blocked boolean NOT NULL DEFAULT FALSE,

	CHECK(fk_member IS NOT NULL::integer + fk_invitation IS NOT NULL::integer + is_blocked::integer = 1)
);
ALTER TABLE squads ADD CONSTRAINT fk_squad_owner
  FOREIGN KEY(id, id_owner) REFERENCES squad_users(id_squad, fk_member) DEFERRABLE;

CREATE TABLE squad_invitations(
  id_squad integer REFERENCES squads ON DELETE CASCADE,
  id_target integer REFERENCES users,
  id_creator integer REFERENCES users,
  PRIMARY KEY(id_squad, id_target, id_creator),
  CHECK(id_creator<>id_target),

  FOREIGN KEY(id_squad, id_creator) REFERENCES squad_users(id_squad, fk_member) DEFERRABLE,
  FOREIGN KEY(id_squad, id_target) REFERENCES squad_users(id_squad, fk_invitation) ON DELETE CASCADE
);
ALTER TABLE squad_users ADD CONSTRAINT fk_squad_invitation_creator
  FOREIGN KEY(id_squad, fk_invitation, id_creator) REFERENCES squad_invitations(id_squad, id_target, id_creator) DEFERRABLE;