DROP TABLE IF EXISTS users, follows, friends, friend_requests, follows, user_bans CASCADE;

CREATE TABLE users(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  password varchar NOT NULL,
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE follows(
  id_follower integer REFERENCES users,
  id_following integer REFERENCES users,
  PRIMARY KEY(id_follower, id_following),

  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE friends(
  id_usera integer REFERENCES users,
  id_userb integer REFERENCES users,
  PRIMARY KEY(id_usera, id_userb),
  CHECK(id_usera < id_userb),

  FOREIGN KEY(id_usera, id_userb) REFERENCES follows,
  FOREIGN KEY(id_userb, id_usera) REFERENCES follows,

  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE friend_requests(
  id_usera integer REFERENCES users,
  id_userb integer REFERENCES users,
  PRIMARY KEY(id_usera, id_userb),
  CHECK(id_usera < id_userb),

	created_by integer REFERENCES users NOT NULL,
  CHECK(created_by IN(id_usera, id_userb)),
  created_at timestamptz NOT NULL DEFAULT NOW()
);

CREATE TABLE user_bans(
  id_usera integer REFERENCES users,
  id_userb integer REFERENCES users,
  PRIMARY KEY(id_usera, id_userb),
  CHECK(id_usera < id_userb),

  created_by integer REFERENCES users NOT NULL,
  CHECK(created_by IN(id_usera, id_userb)),
  created_at timestamptz NOT NULL DEFAULT NOW()
);